### ISSUE TITLE
Crash on build

### ISSUE THREAD

**Issue by BastienBalaud** [NathanGrimaud/epsi-chapeau-front#1]
yarn build --prod                
yarn run v1.6.0
```
$ ng build --prod
Could not find module "@angular-devkit/build-angular" from "/var/webservices/app/epsi-chapeau-front".
Error: Could not find module "@angular-devkit/build-angular" from "/var/webservices/app/epsi-chapeau-front".
    at Object.resolve (/usr/local/share/.config/yarn/global/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/share/.config/yarn/global/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable.subscribe (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/Observable.js:162:69)
    at DoOperator.call (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/Observable.js:159:22)
    at /usr/local/share/.config/yarn/global/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/usr/local/share/.config/yarn/global/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
```

**Comment by BastienBalaud** [comment]
Fix
